#!/bin/bash

S3_URI=
RDS_ENDPOINT=
RDS_DB_NAME=
RDS_DB_USERNAME=
RDS_DB_PASSWORD=

# Update all packages
sudo yum update -y

# Download and extract Flyway
sudo wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz | tar -xvz 


# Create a symbolic link to make Flyway accessible globally (you can skip since you combined it in line 13)
sudo ln -s $(pwd)/flyway-11.1.0/flyway /usr/local/bin

# Create the SQL directory for migrations
sudo mkdir sql

# Download the migration SQL script from AWS S3
sudo aws s3 cp "$S3_URI" sql/

# Run Flyway migration
flyway -url=jdbc:mysql://"$RDS_ENDPOINT":3306/"$RDS_DB_NAME" \
  -user="$RDS_DB_USERNAME" \
  -password="$RDS_DB_PASSWORD" \
  -locations=filesystem:sql \
  migrate




flyway -url=jdbc:mysql://dev-rds-db.c9m4k280i5nt.us-east-1.rds.amazonaws.com:3306/applicationdb2 \
  -user= \
  -password= \
  -locations=filesystem:sql \
  migrate
  
  wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin
